import { expect, spyOn, test } from "bun:test";
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import sharp from "sharp";
import { loadConfig } from "../../src/server/config";
import type { DrawingRecord } from "../../src/server/database";
import { ImageService } from "../../src/server/images";

for (const background of [undefined, "#ff0000"]) {
  for (const [width, height] of [[20, 10], [1, 1]] as const) {
    test(`crops all borders around ${width}x${height} ink on ${background ?? "transparent"} canvas`, async () => {
      const directory = mkdtempSync("/tmp/scrich-crop-test-");
      try {
        const config = loadConfig({ DATA_DIR: directory });
        mkdirSync(config.drawingsDir, { recursive: true });
        mkdirSync(config.cacheDir, { recursive: true });
        const images = new ImageService(config);
        const original = await sharp({
          create: {
            width: 200,
            height: 100,
            channels: 4,
            background: background ?? { r: 0, g: 0, b: 0, alpha: 0 },
          },
        }).composite([{
          input: await sharp({ create: { width, height, channels: 4, background: "black" } }).png()
            .toBuffer(),
          left: 130,
          top: 60,
        }]).png().toBuffer();
        writeFileSync(images.original("1"), original);
        const drawing: DrawingRecord = {
          id: 1,
          shortId: "1",
          createdAt: "2026-01-01",
          visibility: "visible",
          parent: null,
          settings: background ? { background } : {},
        };
        // A derivative generated by the previous pipeline must not be reused.
        const oldCache = join(directory, "cache", "v1");
        mkdirSync(oldCache, { recursive: true });
        writeFileSync(join(oldCache, "1-crop.png"), original);
        writeFileSync(join(oldCache, "1-2x.png"), original);
        for (const factor of [1, 2, 3, 4] as const) {
          const path = await images.resolve(drawing, factor === 1 ? "default" : factor);
          const image = await sharp(path).raw().toBuffer({ resolveWithObject: true });
          expect([image.info.width, image.info.height]).toEqual([
            (width + 40) * factor,
            (height + 40) * factor,
          ]);
          let left = image.info.width, top = image.info.height, right = 0, bottom = 0;
          for (let y = 0; y < image.info.height; y++) {
            for (let x = 0; x < image.info.width; x++) {
              const offset = (y * image.info.width + x) * image.info.channels;
              if (
                image.data[offset] === 0 && image.data[offset + 1] === 0
                && image.data[offset + 2] === 0
              ) {
                left = Math.min(left, x);
                top = Math.min(top, y);
                right = Math.max(right, x);
                bottom = Math.max(bottom, y);
              }
            }
          }
          expect([left, top, image.info.width - 1 - right, image.info.height - 1 - bottom]).toEqual(
            Array(4).fill(20 * factor),
          );
        }
        for (
          const settings of [drawing.settings, {
            ...drawing.settings,
            size: { width: 200, height: 100 },
          }]
        ) {
          const cropped = await images.resolve({ ...drawing, settings }, "cropped");
          const metadata = await sharp(cropped).metadata();
          expect([metadata.width, metadata.height]).toEqual([width, height]);
        }
        expect(new Uint8Array(readFileSync(await images.resolve(drawing, "raw")))).toEqual(
          new Uint8Array(original),
        );
        expect(new Uint8Array(readFileSync(join(oldCache, "1-crop.png")))).toEqual(
          new Uint8Array(original),
        );
        const fixed = await images.resolve(
          { ...drawing, settings: { ...drawing.settings, size: { width: 200, height: 100 } } },
          "default",
        );
        const metadata = await sharp(fixed).metadata();
        expect([metadata.width, metadata.height, metadata.hasAlpha]).toEqual([200, 100, false]);
      } finally {
        rmSync(directory, { recursive: true, force: true });
      }
    });
  }
}

for (const fixedSize of [false, true]) {
  for (const background of [undefined, "#fff", "#ff0000"]) {
    test(`all image variants: size=${fixedSize}, background=${background ?? "default"}`, async () => {
      const directory = mkdtempSync("/tmp/scrich-variants-test-");
      try {
        const config = loadConfig({ DATA_DIR: directory });
        mkdirSync(config.drawingsDir, { recursive: true });
        mkdirSync(config.cacheDir, { recursive: true });
        const images = new ImageService(config);
        // Transparent surroundings exercise export compositing even with saved background settings.
        const raw = await sharp({
          create: {
            width: 60,
            height: 40,
            channels: 4,
            background: { r: 0, g: 0, b: 0, alpha: 0 },
          },
        }).composite([{
          input: await sharp({
            create: { width: 10, height: 8, channels: 4, background: "#00ff00" },
          }).png().toBuffer(),
          left: 25,
          top: 12,
        }]).png().toBuffer();
        const oldCache = join(directory, "cache/v2");
        mkdirSync(oldCache, { recursive: true });
        writeFileSync(join(oldCache, "1-2x.png"), raw);
        // Margin is a canvas layout option; it must not change any export dimensions.
        for (const [index, margin] of [undefined, 7, 40].entries()) {
          const shortId = String(index + 1);
          writeFileSync(images.original(shortId), raw);
          const drawing: DrawingRecord = {
            id: index + 1,
            shortId,
            createdAt: "2026-01-01",
            visibility: "visible",
            parent: null,
            settings: {
              foreground: "#00ff00",
              ...(background ? { background } : {}),
              ...(margin ? { margin } : {}),
              ...(fixedSize ? { size: { width: 60, height: 40 } } : {}),
            },
          };
          expect(new Uint8Array(readFileSync(await images.resolve(drawing, "raw"))))
            .toEqual(new Uint8Array(raw));
          for (const mode of ["default", "cropped", 2, 3, 4] as const) {
            const path = await images.resolve(drawing, mode);
            const metadata = await sharp(path).metadata();
            const factor = typeof mode === "number" ? mode : 1;
            const base = mode === "cropped" ? [10, 8] : fixedSize ? [60, 40] : [50, 48];
            expect([metadata.width, metadata.height, metadata.hasAlpha])
              .toEqual([base[0]! * factor, base[1]! * factor, false]);
            const pixels = await sharp(path).raw().toBuffer();
            const expectedCorner = mode === "cropped"
              ? [0, 255, 0]
              : background === "#ff0000"
              ? [255, 0, 0]
              : [255, 255, 255];
            expect([...pixels.subarray(0, 3)]).toEqual(expectedCorner);
          }
        }
      } finally {
        rmSync(directory, { recursive: true, force: true });
      }
    });
  }
}

test("exports a 2880x1800 drawing at 4x and respects a configured lower limit", async () => {
  const directory = mkdtempSync("/tmp/scrich-large-export-");
  try {
    const config = loadConfig({ DATA_DIR: directory });
    mkdirSync(config.drawingsDir, { recursive: true });
    mkdirSync(config.cacheDir, { recursive: true });
    const images = new ImageService(config);
    await sharp({ create: { width: 2880, height: 1800, channels: 3, background: "black" } })
      .png().toFile(images.original("1"));
    const drawing: DrawingRecord = {
      id: 1,
      shortId: "1",
      createdAt: "2026-01-01",
      visibility: "visible",
      parent: null,
      settings: { size: { width: 2880, height: 1800 } },
    };
    const restricted = new ImageService({ ...config, maxExportPixels: 32_000_000 });
    await expect(restricted.resolve(drawing, 4)).rejects.toThrow("32000000 pixel export limit");
    const path = await images.resolve(drawing, 4);
    const metadata = await sharp(path).metadata();
    expect([metadata.width, metadata.height]).toEqual([11520, 7200]);
    expect(await images.resolve(drawing, 4)).toBe(path);
    await expect(restricted.resolve(drawing, 4)).rejects.toThrow("32000000 pixel export limit");
  } finally {
    rmSync(directory, { recursive: true, force: true });
  }
}, 30_000);

test("zoom generation is serialized and a failed zoom releases the queue", async () => {
  const directory = mkdtempSync("/tmp/scrich-zoom-queue-");
  const config = loadConfig({ DATA_DIR: directory });
  mkdirSync(config.drawingsDir, { recursive: true });
  mkdirSync(config.cacheDir, { recursive: true });
  const images = new ImageService(config);
  let active = 0;
  let peak = 0;
  const toFile = sharp.prototype.toFile;
  const spy = spyOn(sharp.prototype, "toFile").mockImplementation(
    async function(this: sharp.Sharp, path: string) {
      if (!/-[234]x\.png\./.test(path)) return await toFile.call(this, path);
      active++;
      peak = Math.max(peak, active);
      try {
        await Bun.sleep(20);
        if (path.includes("-2x.png.")) throw new Error("Synthetic generation failure");
        return await toFile.call(this, path);
      } finally {
        active--;
      }
    },
  );
  try {
    await sharp({ create: { width: 20, height: 20, channels: 3, background: "black" } })
      .png().toFile(images.original("1"));
    const drawing: DrawingRecord = {
      id: 1,
      shortId: "1",
      createdAt: "2026-01-01",
      visibility: "visible",
      parent: null,
      settings: { size: { width: 20, height: 20 } },
    };
    const results = await Promise.allSettled(
      [2, 3, 4].map((factor) => images.resolve(drawing, factor as 2 | 3 | 4)),
    );
    expect(results.map((result) => result.status)).toEqual(["rejected", "fulfilled", "fulfilled"]);
    expect(peak).toBe(1);
    expect(active).toBe(0);
  } finally {
    spy.mockRestore();
    rmSync(directory, { recursive: true, force: true });
  }
});
